---
label: Product Details
hide_body: true
fields:
- name: permalink
  type: text
  label: Permalink
  config:
    required: true
- name: layout
  type: text
  hidden: true
  label: layout
  default: product-details
  config:
    required: true
